//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ch1_1.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CH1_1TYPE                   129
#define IDD_DLG_GEOTrans                130
#define IDD_DLG_GEOZoom                 131
#define IDD_DLG_GEORota                 132
#define IDD_DLG_Smooth                  133
#define IDD_DLG_MidianFilter            134
#define IDD_DLG_LinerPara               135
#define IDD_DLG_PointWin                136
#define IDD_DLG_Intensity               137
#define IDD_DLG_PointStre               138
#define IDD_DLG_PointThre               140
#define IDD_DLG_Color                   141
#define IDD_DLG_THRE                    142
#define IDD_DLG_Huffman                 143
#define IDD_DLG_Shannon                 144
#define IDD_DLG_MORPHClose              150
#define IDD_DLG_MORPHDilation           151
#define IDD_DLG_MORPHErosion            152
#define IDD_DLG_MORPHOpen               153
#define IDD_DLG_CodeGIF                 155
#define IDC_EDIT_XOffset                1000
#define IDC_EDIT_YOffset                1001
#define IDC_EDIT_XZoom                  1002
#define IDC_EDIT_YZoom                  1003
#define IDC_EDIT_Rotate                 1004
#define IDC_RAD1                        1005
#define IDC_RAD2                        1006
#define IDC_RAD3                        1007
#define IDC_RAD4                        1008
#define IDC_EDIT_FH                     1009
#define IDC_EDIT_FW                     1010
#define IDC_EDIT_TEMPH                  1010
#define IDC_EDIT_FMX                    1011
#define IDC_EDIT_TEMPW                  1011
#define IDC_EDIT_A                      1011
#define IDC_EDIT_FMY                    1012
#define IDC_EDIT_V0                     1012
#define IDC_EDIT_B                      1012
#define IDC_EDIT_V1                     1013
#define IDC_COORD                       1013
#define IDC_EDIT_V2                     1014
#define IDC_EDIT_Low                    1014
#define IDC_EDIT_V3                     1015
#define IDC_EDIT_Up                     1015
#define IDC_EDIT_V4                     1016
#define IDC_EDIT_LowGray                1016
#define IDC_EDIT_UpGray                 1017
#define IDC_EDIT_V5                     1017
#define IDC_EDIT_X1                     1018
#define IDC_EDIT_V6                     1018
#define IDC_EDIT_Y1                     1019
#define IDC_EDIT_V7                     1019
#define IDC_EDIT_X2                     1020
#define IDC_EDIT_V8                     1020
#define IDC_EDIT_Thre                   1020
#define IDC_EDIT_Y2                     1021
#define IDC_EDIT_V9                     1021
#define IDC_COLOR_LIST                  1021
#define IDC_EDIT_V10                    1022
#define IDC_LST_Table                   1022
#define IDC_EDIT_V11                    1023
#define IDC_STATIC1                     1023
#define IDC_EDIT_V12                    1024
#define IDC_STATIC2                     1024
#define IDC_EDIT_V13                    1025
#define IDC_STATIC3                     1025
#define IDC_EDIT_V14                    1026
#define IDC_EDIT1                       1026
#define IDC_EDIT_V15                    1027
#define IDC_EDIT2                       1027
#define IDC_EDIT_FileName               1027
#define IDC_EDIT_V16                    1028
#define IDC_EDIT3                       1028
#define IDC_btnSaveAs                   1028
#define IDC_EDIT_V17                    1029
#define IDC_RADIO1                      1029
#define IDC_EDIT_V18                    1030
#define IDC_RADIO2                      1030
#define IDC_EDIT_V19                    1031
#define IDC_EDIT_V20                    1032
#define IDC_EDIT_V21                    1033
#define IDC_EDIT_V22                    1034
#define IDC_EDIT_V23                    1035
#define IDC_EDIT_V24                    1036
#define IDC_EDIT_TEMPC                  1038
#define IDC_EDIT_MX                     1039
#define IDC_EDIT_MY                     1040
#define IDC_Hori                        1041
#define IDC_Vert                        1042
#define IDC_custom                      1043
#define IDC_Structure1                  1044
#define IDC_Structure2                  1045
#define IDC_Structure3                  1046
#define IDC_Structure4                  1047
#define IDC_Structure5                  1048
#define IDC_Structure6                  1049
#define IDC_Structure7                  1050
#define IDC_Structure8                  1051
#define IDC_Structure9                  1052
#define ID_GEOM_TRAN                    32771
#define ID_GEOM_ROTA                    32772
#define ID_GEOM_MIRR                    32773
#define ID_GEOM_MIRH                    32774
#define ID_GEOM_MIRV                    32775
#define ID_GEOM_TRPO                    32776
#define ID_GEOM_ZOOM                    32777
#define ID_FILE_REOPEN                  32778
#define ID_TEMP_SMOOTH                  32779
#define ID_ENHA_SMOOTH                  32779
#define ID_TEMP_SHARP                   32780
#define ID_ENHA_SHARP                   32780
#define ID_TEMP_MidianF                 32782
#define ID_ENHA_MidianF                 32782
#define ID_POINT_STRE                   32783
#define ID_POINT_EQUA                   32784
#define ID_POINT_WIND                   32785
#define ID_POINT_INVERT                 32786
#define ID_POINT_LINER                  32787
#define ID_VIEW_INTENSITY               32788
#define ID_POINT_THRE                   32789
#define ID_ENHA_COLOR                   32790
#define ID_FREQ_FOUR                    32791
#define ID_FREQ_DCT                     32792
#define ID_FREQ_WALH                    32793
#define ID_FILE_256ToGray               32794
#define ID_ENHA_GRADSHARP               32795
#define ID_CODE_HUFFMAN                 32796
#define ID_CODE_RLE                     32799
#define ID_CODE_IRLE                    32800
#define ID_CODE_JEPG                    32801
#define ID_CODE_IJEPG                   32802
#define ID_CODE_SHANNON                 32803
#define ID_MORPH_EROSION                32804
#define ID_MORPH_DILATION               32805
#define ID_MORPH_OPEN                   32806
#define ID_MORPH_CLOSE                  32807
#define ID_MORPH_THINING                32808
#define ID_EDGE_ROBERT                  32809
#define ID_EDGE_SOBEL                   32810
#define ID_EDGE_PREWITT                 32811
#define ID_EDGE_KIRSCH                  32812
#define ID_EDGE_GAUSS                   32813
#define ID_EDGE_HOUGH                   32814
#define ID_EDGE_CONTOUR                 32815
#define ID_EDGE_FILL                    32816
#define ID_EDGE_TRACE                   32817
#define ID_DETECT_THRESHOLD             32818
#define ID_DETECT_HPROJECTION           32819
#define ID_DETECT_VPROJECTION           32820
#define ID_DETECT_MINUS                 32821
#define ID_DETECT_TEMPLATE              32822
#define ID_RESTORE_BLUR                 32823
#define ID_RESTORE_NOISEBLUR            32824
#define ID_RESTORE_INVERSE              32825
#define ID_RESTORE_WIENER               32826
#define ID_RESTORE_RANDOMNOISE          32827
#define ID_RESTORE_SALTNOISE            32828
#define ID_CODE_LZW                     32829
#define ID_CODE_ILZW                    32830
#define ID_EDGE_FILL2                   32831

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
